# Generated by Django 3.2.9 on 2021-11-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome do projeto')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descriação do projeto')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo?')),
            ],
        ),
    ]
